spring:
  # supposedly auto finishes app, but actually not
  main:
    web-application-type: none

  application:
    name: consoledb

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: developer
    password: password

logging:
  level:
    root: WARN
